### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by tomjaguarpaw**

### CODE REVIEW

**Comment by tomjaguarpaw** [comment]
Code says `y1 = :(1 * 2)`

**Comment by MikeInnes** [comment]
:+1: Thanks!

**Comment by MikeInnes** [comment]
Although having just merged this, note that you actually need to edit the original markdown files rather than the notebooks. Otherwise this'll just get overwritten next time we generate them.

**Comment by tomjaguarpaw** [comment]
Oh, where are the Markdown files?  Are they in a separate repo?  I don't see them in this one.

**Comment by MikeInnes** [comment]
They are actually not markdown, but julia files in the [src folder](https://github.com/MikeInnes/diff-zoo/tree/master/src).

**Comment by tomjaguarpaw** [comment]
OK, new PR submitted: https://github.com/MikeInnes/diff-zoo/pull/13

**Pull request merged**
